### ISSUE TITLE
SVG 的暗色模式支持 SVG's dark mode support

### ISSUE THREAD

**Issue by youli42** [SiriusXT/trilium-drawio#9]
After editing with the default dark mode, the saved SVG seems to use the light mode by default in the Trilium preview, which results in poor readability under the dark theme. May I ask if there is any way for me to enable the default use of dark mode or follow the system mode to display the SVG preview?

默认使用暗色模式编辑后，保存的SVG在Trilium预览中似乎默认使用了亮色模式，这在暗色主题下可读性较差。请问我是否有什么方法可以允许默认使用暗色模式或者跟随系统模式，显示SVG预览？

<img width="1780" height="555" alt="Image" src="https://github.com/user-attachments/assets/ff010029-3196-4455-a41e-cfcd3a575e11" />

**Comment by youli42** [comment]
经过测试发现，这并不是插件的问题，而是 Trilium 在应用深色主题后，会自动将图片进行反色处理，这不好，我正在寻找关闭这个功能的开关

After testing, it turns out that this is not an issue with the plugin. Instead, when Trilium applies the dark theme, it automatically inverts the colors of images. This is not good, and I am looking for a switch to turn off this feature.

**Comment by youli42** [comment]
After some testing, I can't locate the problem. The color inversion only occurs when directly viewing this attachment; it doesn't happen when viewing other attachments, nor does it happen when inserting this file into a note.

**Comment by SarrLight** [comment]
<img width="949" height="658" alt="Image" src="https://github.com/user-attachments/assets/a4b73054-6e45-4283-8d2a-b1683c384f29" />我也遇到了相同的问题，最后我发现反色处理是因为drawio默认开启了自适应颜色，这会导致制作的svg文件内置了light和dark两种显色模式，于是把svg文件导入到其他软件时可能会显示与之前在drawio中不同的颜色。我把自适应颜色改成“无”之后，问题就解决了。
I also encountered the same issue. In the end, I found that the color inversion was because drawio enables adaptive colors by default. This causes the created SVG files to have built-in light and dark color modes, so when the SVG files are imported into other software, they may display different colors from what they showed in drawio before. After I changed the adaptive color setting to "None", the problem was solved.

**Comment by SarrLight** [comment]
<img width="434" height="824" alt="Image" src="https://github.com/user-attachments/assets/d620e44c-ce2b-49e5-af54-1ad99b4fb02e" />
哦哦，现在我发现drawio在调整图形颜色时可以同时指定light和dark模式下的颜色，如上图所示，太阳后面对应的是light模式下的颜色，月亮后面对应的是dark模式下的颜色（可能需要点击”高级“才能看到）
Oh, now I've noticed that when adjusting the color of a shape in drawio, you can specify colors for both light and dark modes at the same time, as shown in the image above. The color corresponding to the sun is for the light mode, and the color corresponding to the moon is for the dark mode (you may need to click "Advanced" to see this).

**Comment by youli42** [comment]
经过一些测试，我认为我的预览问题与 draw.io 无关：
1. 预览模式下，draw.io 文件被转换为 .svg 文件，此时渲染效果由 Trilium 处理
2. 我的 Trilium 使用暗色主题，这个模式下 .svg 图片被强制反色，即使我更改了 draw.io 的相关设置

After some testing, I believe my preview issue has nothing to do with draw.io:
1. In preview mode, the draw.io file is converted to an .svg file, and the rendering effect is handled by Trilium at this point.
2. My Trilium uses a dark theme, and in this mode, .svg images are forced to invert colors, even if I change the relevant settings in draw.io.

https://github.com/user-attachments/assets/f3f4eca8-1559-40fa-bf9b-deb7649cfbaf

**Comment by SiriusXT** [comment]
我也不清楚，有没有装过一个Dark-mode-img-color-conversion.js的widget?

**Comment by youli42** [comment]
真的有这个控件，就是您的主题中的？但我将其删除后没有变化，svg在被单独预览的时候仍然会被强制反向色。但我已经无所谓了，目前预览都将其插入到文章中，在文章中预览是正确的。谢谢大佬。

There really is this widget, and it's in your theme? But after I deleted it, there was no change; when the SVG is previewed alone, it still gets forced to invert colors. But I don't care anymore. Currently, when previewing, I just insert it into the article, and the preview in the article is correct. Thank you, sir.
